// What the runtime understands: elements, attributes, directives, honored CSS.
//
// Two copies of this exist on purpose, and the order matters.
//
//   1. `vocabulary.json`, generated by `rux vocab` and checked in. It is what
//      makes completions work the moment the extension is installed, before
//      `cargo install ruxlang` has finished, and it is what `scripts/sync-vocabulary.sh`
//      regenerates and CI checks is current.
//   2. Whatever `rux vocab` prints on this machine, read once per session and
//      preferred when it is there. Someone running a Rux built from a branch
//      gets that branch's vocabulary, not the one their extension shipped with.
//
// The reason for any of this is the `<image>` bug: the extension used to carry
// a hand-kept copy of the formatter's void-tag list, inherited HTML's `img`,
// missed Rux's `<image>`, and over-indented for two releases. A completion list
// that offers a CSS property the runtime warns is unhonored would be the same
// mistake with a friendlier face.

const fs = require('fs');
const path = require('path');

/** The generated copy, read from disk once. */
let baked = null;
/** What `rux vocab` said this session, or `null` if it has not been asked yet. */
let live = null;
let liveAsked = false;

function readBaked() {
  if (baked) return baked;
  try {
    baked = JSON.parse(fs.readFileSync(path.join(__dirname, 'vocabulary.json'), 'utf8'));
  } catch (e) {
    // A packaging accident should degrade to no completions, not to a broken
    // extension: formatting and diagnostics have nothing to do with this file.
    baked = EMPTY;
  }
  return baked;
}

const EMPTY = {
  elements: [],
  globalAttributes: [],
  directives: [],
  elementAttributes: {},
  scriptGlobals: [],
  pseudoClasses: [],
  voidTags: [],
  cssProperties: [],
  cssValues: {},
  cssPropertyDocs: [],
  animatableProperties: [],
  easings: [],
  elementProperties: [],
  elementMethods: [],
  valueMethods: [],
};

/**
 * Ask the installed binary what it understands. Called once per session, and
 * deliberately not on a timer: a vocabulary that changes under a running editor
 * would make completions non-reproducible for no benefit. Reload the window
 * after upgrading Rux, the same as for any other extension input.
 */
function refreshFromBinary(runRux) {
  if (liveAsked) return;
  liveAsked = true;

  // Ask what the binary supports before asking it for anything.
  //
  // `rux vocab` on a binary that predates the subcommand is not a no-op. The
  // CLI treats an unrecognised first argument as a path to run, because
  // `rux app.rux` is the form every doc teaches, so `vocab` is read as a
  // document name. On 0.6.0 that **opens a GUI window** and exits 0, which is
  // both invisible to an exit-code check and the worst possible outcome:
  // opening a `.rux` file in the editor launched a Rux window.
  //
  // `--help` is safe on every version ever published: it prints and exits, and
  // no version has ever done anything else with it.
  let help;
  try {
    help = runRux(['--help']);
  } catch (e) {
    return;
  }
  if (!help || !help.ok || !(help.stdout || '').includes('vocab')) return;

  let result;
  try {
    result = runRux(['vocab']);
  } catch (e) {
    return;
  }
  if (!result || !result.ok || result.code !== 0) return;
  try {
    const parsed = JSON.parse(result.stdout);
    if (parsed && Array.isArray(parsed.elements) && parsed.elements.length) {
      live = parsed;
    }
  } catch (e) {
    /* keep the baked copy */
  }
}

/**
 * The vocabulary in force: the binary's answers, with the bundled copy filling
 * any field the binary did not emit.
 *
 * This used to be `live || baked`, all or nothing, and that is wrong whenever
 * **the extension is newer than the binary** — which is the normal case while
 * both are being developed, and it happened here. `cssPropertyDocs` was added
 * to the extension and to `rux vocab` together, but the `rux` on PATH had been
 * built an hour earlier. It emitted every other field, so it won outright, and
 * the property descriptions the extension shipped with were discarded. The
 * completion list fell back to "honored by the runtime" with no explanation
 * available anywhere.
 *
 * Per field, the binary still wins whenever it says anything, so a branch build
 * with a new element or a dropped CSS property is still authoritative about it.
 * What it cannot do any more is silently remove a whole capability by being old.
 */
function current() {
  const baked = readBaked();
  if (!live) return baked;

  const merged = { ...baked };
  for (const [key, value] of Object.entries(live)) {
    const empty =
      value === undefined ||
      value === null ||
      (Array.isArray(value) && value.length === 0);
    if (!empty) merged[key] = value;
  }
  return merged;
}

/** Element entries: `{ name, detail, doc }`. */
function elements() {
  return current().elements || [];
}

/** Attributes valid on any element. */
function globalAttributes() {
  return current().globalAttributes || [];
}

/** `r-for`, `r-if`, `r-model` and the rest. */
function directives() {
  return current().directives || [];
}

/** Attributes that only mean something on `tag`. */
function attributesFor(tag) {
  return (current().elementAttributes || {})[tag] || [];
}

/** `signal`, `computed`, `navigate` and the rest of what script can call. */
function scriptGlobals() {
  return current().scriptGlobals || [];
}

/** CSS properties the runtime honors. Anything else it parses and warns about. */
function cssProperties() {
  return current().cssProperties || [];
}

/**
 * The keyword values for one property, or `[]` for a property whose values are
 * not a closed set.
 *
 * Empty is the honest answer for `width` and `color`: a list of guesses there
 * would be worse than none, because it would read as the whole set.
 */
function cssValues(property) {
  return (current().cssValues || {})[property] || [];
}

/**
 * What one CSS property does, as `{ name, detail, doc }`, or `null`.
 *
 * `detail` is the one-line effect, `doc` says where it applies and how Rux
 * differs from CSS. The completion list used to show "honored by the runtime"
 * for every property, which tells the reader the editor approves of the word
 * and nothing about what setting it will do.
 */
function cssProperty(name) {
  return (current().cssPropertyDocs || []).find((p) => p.name === name) || null;
}

/** The pseudo-classes a selector may name, as `{ name, detail, doc }`. */
function pseudoClasses() {
  return current().pseudoClasses || [];
}

/** What `transition` can name. Anything else in a `transition` does nothing. */
function animatableProperties() {
  return current().animatableProperties || [];
}

/** The easing keywords, for the third slot of a `transition`. */
function easings() {
  return current().easings || [];
}

/**
 * Tags that never nest, so nothing should ever write a closing tag for them.
 * `image` is in here and `img` is too; the HTML names cost nothing and pasted
 * markup is common.
 */
function isVoid(tag) {
  return (current().voidTags || []).includes(tag);
}

/**
 * What an element handle from `query()` offers: its readable properties, then
 * its actions.
 *
 * Two lists rather than one because they behave differently and the difference
 * is the thing worth teaching: a property is a read of the frame already on
 * screen, and an action is recorded and applied after the handler returns.
 */
function elementMembers() {
  const c = current();
  return (c.elementProperties || [])
    .map((e) => ({ ...e, kind: 'property' }))
    .concat((c.elementMethods || []).map((e) => ({ ...e, kind: 'method' })));
}

/**
 * Methods on strings and arrays: JavaScript's names, which is not a detail.
 * rhai's own string methods share some of these spellings and mutate in place,
 * and Rux shadows them with returning versions.
 */
function valueMethods() {
  return current().valueMethods || [];
}

/** Which copy is in use, for the status shown in `Rux: Show Vocabulary`. */
function source() {
  return live ? `rux vocab (${live.version || 'unknown version'})` : 'bundled with the extension';
}

/**
 * Set the "live" vocabulary directly, for the merge test.
 *
 * The merge is the part with a history of being wrong, and driving it through
 * `refreshFromBinary` would mean faking a subprocess to test a pure function.
 */
function __setLiveForTest(value) {
  live = value;
  liveAsked = true;
}

module.exports = {
  refreshFromBinary,
  __setLiveForTest,
  elements,
  globalAttributes,
  directives,
  attributesFor,
  scriptGlobals,
  cssProperties,
  cssValues,
  cssProperty,
  pseudoClasses,
  animatableProperties,
  easings,
  elementMembers,
  valueMethods,
  isVoid,
  source,
};
