// What the runtime understands: elements, attributes, directives, honored CSS.
//
// Two copies of this exist on purpose, and the order matters.
//
//   1. `vocabulary.json`, generated by `rux vocab` and checked in. It is what
//      makes completions work the moment the extension is installed, before
//      `cargo install ruxlang` has finished, and it is what `scripts/sync-vocabulary.sh`
//      regenerates and CI checks is current.
//   2. Whatever `rux vocab` prints on this machine, read once per session and
//      preferred when it is there. Someone running a Rux built from a branch
//      gets that branch's vocabulary, not the one their extension shipped with.
//
// The reason for any of this is the `<image>` bug: the extension used to carry
// a hand-kept copy of the formatter's void-tag list, inherited HTML's `img`,
// missed Rux's `<image>`, and over-indented for two releases. A completion list
// that offers a CSS property the runtime warns is unhonored would be the same
// mistake with a friendlier face.

const fs = require('fs');
const path = require('path');

/** The generated copy, read from disk once. */
let baked = null;
/** What `rux vocab` said this session, or `null` if it has not been asked yet. */
let live = null;
let liveAsked = false;

function readBaked() {
  if (baked) return baked;
  try {
    baked = JSON.parse(fs.readFileSync(path.join(__dirname, 'vocabulary.json'), 'utf8'));
  } catch (e) {
    // A packaging accident should degrade to no completions, not to a broken
    // extension: formatting and diagnostics have nothing to do with this file.
    baked = EMPTY;
  }
  return baked;
}

const EMPTY = {
  elements: [],
  globalAttributes: [],
  directives: [],
  elementAttributes: {},
  scriptGlobals: [],
  voidTags: [],
  cssProperties: [],
};

/**
 * Ask the installed binary what it understands. Called once per session, and
 * deliberately not on a timer: a vocabulary that changes under a running editor
 * would make completions non-reproducible for no benefit. Reload the window
 * after upgrading Rux, the same as for any other extension input.
 */
function refreshFromBinary(runRux) {
  if (liveAsked) return;
  liveAsked = true;

  // Ask what the binary supports before asking it for anything.
  //
  // `rux vocab` on a binary that predates the subcommand is not a no-op. The
  // CLI treats an unrecognised first argument as a path to run, because
  // `rux app.rux` is the form every doc teaches, so `vocab` is read as a
  // document name. On 0.6.0 that **opens a GUI window** and exits 0, which is
  // both invisible to an exit-code check and the worst possible outcome:
  // opening a `.rux` file in the editor launched a Rux window.
  //
  // `--help` is safe on every version ever published: it prints and exits, and
  // no version has ever done anything else with it.
  let help;
  try {
    help = runRux(['--help']);
  } catch (e) {
    return;
  }
  if (!help || !help.ok || !/vocab/.test(help.stdout || '')) return;

  let result;
  try {
    result = runRux(['vocab']);
  } catch (e) {
    return;
  }
  if (!result || !result.ok || result.code !== 0) return;
  try {
    const parsed = JSON.parse(result.stdout);
    if (parsed && Array.isArray(parsed.elements) && parsed.elements.length) {
      live = parsed;
    }
  } catch (e) {
    /* keep the baked copy */
  }
}

function current() {
  return live || readBaked();
}

/** Element entries: `{ name, detail, doc }`. */
function elements() {
  return current().elements || [];
}

/** Attributes valid on any element. */
function globalAttributes() {
  return current().globalAttributes || [];
}

/** `r-for`, `r-if`, `r-model` and the rest. */
function directives() {
  return current().directives || [];
}

/** Attributes that only mean something on `tag`. */
function attributesFor(tag) {
  return (current().elementAttributes || {})[tag] || [];
}

/** `signal`, `computed`, `navigate` and the rest of what script can call. */
function scriptGlobals() {
  return current().scriptGlobals || [];
}

/** CSS properties the runtime honors. Anything else it parses and warns about. */
function cssProperties() {
  return current().cssProperties || [];
}

/**
 * Tags that never nest, so nothing should ever write a closing tag for them.
 * `image` is in here and `img` is too; the HTML names cost nothing and pasted
 * markup is common.
 */
function isVoid(tag) {
  return (current().voidTags || []).includes(tag);
}

/** Which copy is in use, for the status shown in `Rux: Show Vocabulary`. */
function source() {
  return live ? `rux vocab (${live.version || 'unknown version'})` : 'bundled with the extension';
}

module.exports = {
  refreshFromBinary,
  elements,
  globalAttributes,
  directives,
  attributesFor,
  scriptGlobals,
  cssProperties,
  isVoid,
  source,
};
