//! Rust from Rux's typed IR: step 9 of `docs/11-next.md`.
//!
//! [`generate`] writes a Rust module for a unit's functions. Each becomes a
//! Rust function running inside Rux's interpreter through `aot` (the
//! `rux_script::aot` module, reached by whatever path the generated crate
//! names it), in a frame of the interpreter's own. A statement whose every
//! expression the generator understands is compiled; any other statement is
//! handed back to the interpreter by its place in the function
//! (`aot::find`), in the same frame, so what is compiled and what is not can
//! sit side by side in one function. Control flow, literals, locals, state,
//! operators and calls to the file's own functions are compiled; the rest
//! (fields, indexes, methods, closures, built-ins) is interpreted for now,
//! and [`Output`] counts both.
//!
//! The semantics are the interpreter's by construction: every operator,
//! read and write goes through the same `aot` call the interpreter makes,
//! steps are counted where it counts them, and a failure is placed at the
//! statement the interpreter would place it at.

use std::fmt::Write as _;

use rux_ir::ir::{Block, Callee, Expr, ExprKind, Func, Root, Stmt, StmtKind, Unit};

/// What [`generate`] wrote.
#[derive(Clone, Debug, Default)]
pub struct Output {
    /// The module's text.
    pub code: String,
    /// How many functions were compiled, and how many were left to the
    /// interpreter (`async fn`s, which run from their resumable form).
    pub functions: usize,
    pub skipped: usize,
    /// How many statements were compiled, and how many handed back.
    pub compiled: usize,
    pub handed_back: usize,
}

/// A module compiling `unit`'s functions, registered under `hash` by its
/// `install()`. `aot` is the path the generated code names the
/// `rux_script::aot` module by: `rux_runtime::aot` in an app's wrapper crate.
pub fn generate(unit: &Unit, hash: u64, aot: &str) -> Output {
    let mut g = Gen { unit, out: Output::default(), code: String::new() };
    let _ = writeln!(
        g.code,
        "// Generated by rux-codegen from a unit whose text hashes to {hash:#018x}.\n\
         // Edits are overwritten on the next build. See docs/11-next.md, step 9.\n\
         #![allow(unused_imports, unused_macros, unused_mut, unused_variables, unused_braces, unused_parens, unreachable_code, \
         non_snake_case, clippy::all)]\n\
         use {aot}::{{self as aot, Cx, Flow, V, R, BinOp, UnOp}};\n\
         \n\
         /// A fallible step of a statement at `$s..$e`: its failure placed there.\n\
         macro_rules! t {{\n    ($x:expr, $s:expr, $e:expr) => {{\n        match $x {{\n            Ok(v) => v,\n            // u32::MAX: a function's value, whose failure its caller places.
            Err(err) => return Err(if $s == u32::MAX {{ err }} else {{ aot::at(err, $s, $e) }}),\n        }}\n    }};\n}}\n"
    );
    let mut table = Vec::new();
    for (id, f) in unit.fns.iter().enumerate() {
        if f.is_async {
            g.out.skipped += 1;
            continue;
        }
        g.func(id as u32, f);
        table.push(format!("({id}, {}, f{id})", f.body.locals.len()));
        g.out.functions += 1;
    }
    let _ = writeln!(
        g.code,
        "\nstatic FNS: &[aot::Entry] = &[{}];\n\n\
         /// Register these functions for the text they were generated from.\n\
         pub fn install() {{\n    aot::register({hash:#018x}, FNS);\n}}",
        table.join(", ")
    );
    g.out.code = g.code;
    g.out
}

struct Gen<'u> {
    unit: &'u Unit,
    out: Output,
    code: String,
}

/// Where a statement is and what it may do, for the code around it.
#[derive(Clone)]
struct Place {
    func: u32,
    /// Its path in the function's body, as `aot::find` reads one.
    path: Vec<u32>,
    /// Whether a Rust loop of the generated code is around it.
    in_loop: bool,
    /// How deep in generated loops, for names that must not collide.
    depth: usize,
}

impl Gen<'_> {
    fn func(&mut self, id: u32, f: &Func) {
        let _ = writeln!(self.code, "\n/// `{}`", f.name.replace('\n', " "));
        let _ = writeln!(self.code, "fn f{id}(cx: &mut Cx) -> R<V> {{");
        let place = Place { func: id, path: Vec::new(), in_loop: false, depth: 0 };
        let body = self.block(&f.body.block, &place, None, true);
        self.code.push_str(&body);
        self.code.push_str("}\n");
    }

    /// `b`'s statements. With `value`, the block's value is the function's
    /// result and is returned; otherwise it is worked out and dropped, as the
    /// interpreter does with a block run as a statement. `at` is the
    /// enclosing statement's place, where a failure in that value is placed.
    fn block(&mut self, b: &Block, place: &Place, at: Option<(u32, u32)>, value: bool) -> String {
        let mut s = String::new();
        let last = b.stmts.len();
        for (i, st) in b.stmts.iter().enumerate() {
            let mut p = place.clone();
            p.path.push(i as u32);
            if i + 1 == last && b.ty.is_some() {
                if let StmtKind::Expr(e) = &st.kind {
                    let (start, end) = at.unwrap_or((st.at.start, st.at.end));
                    // A function's value: its failure is its caller's to
                    // place, as the interpreter leaves it.
                    let (start, end) = if value { (u32::MAX, u32::MAX) } else { (start, end) };
                    match (self.expr(e, start, end), value, at) {
                        (Some(x), true, _) => {
                            self.out.compiled += 1;
                            let _ = writeln!(s, "cx.tick()?;\nreturn Ok({x});");
                        }
                        (Some(x), false, Some(_)) => {
                            self.out.compiled += 1;
                            let _ = writeln!(s, "cx.tick()?;\nlet _ = {x};");
                        }
                        _ => {
                            self.out.handed_back += 1;
                            let path = path_of(&p.path);
                            if value {
                                let _ = writeln!(s, "return cx.value({}, &{path});", p.func);
                            } else {
                                // Worked out as the interpreter works out a
                                // block's value, and dropped; a failure is
                                // placed at the enclosing statement.
                                let _ = writeln!(s, "let _ = t!(cx.value({}, &{path}), {start}, {end});", p.func);
                            }
                        }
                    }
                    return s;
                }
            }
            s.push_str(&self.stmt(st, &p));
        }
        if value {
            s.push_str("Ok(V::None)\n");
        }
        s
    }

    /// The statement handed back to the interpreter, in this frame, with
    /// what leaves it passed on.
    fn hand_back(&self, p: &Place) -> String {
        let path = path_of(&p.path);
        if p.in_loop {
            format!(
                "match cx.stmt({}, &{path}) {{ Ok(()) => {{}} Err(Flow::Break) => break, \
                 Err(Flow::Continue) => continue, Err(e) => return Err(e) }}",
                p.func
            )
        } else {
            format!("cx.stmt({}, &{path})?;", p.func)
        }
    }

    fn stmt(&mut self, st: &Stmt, p: &Place) -> String {
        match self.try_stmt(st, p) {
            Some(code) => {
                self.out.compiled += 1;
                code
            }
            None => {
                self.out.handed_back += 1;
                format!("{}\n", self.hand_back(p))
            }
        }
    }

    /// `st` compiled, or `None` when anything in it is not understood.
    fn try_stmt(&mut self, st: &Stmt, p: &Place) -> Option<String> {
        let (s, e) = (st.at.start, st.at.end);
        let tick = format!("t!(cx.tick(), {s}, {e});\n");
        let body = match &st.kind {
            StmtKind::Expr(x) => format!("let _ = {};\n", self.expr(x, s, e)?),
            StmtKind::Let { local, value } => {
                let v = match value {
                    Some(v) => self.expr(v, s, e)?,
                    None => "V::None".to_string(),
                };
                format!("let __v = {v};\ncx.set({}, __v);\n", local.0)
            }
            StmtKind::Assign { place, op, value } if place.steps.is_empty() => {
                let v = self.expr(value, s, e)?;
                let op = match op {
                    Some(op) => format!("Some(BinOp::{op:?})"),
                    None => "None".to_string(),
                };
                let call = match place.root {
                    Root::Local(l) => format!("cx.assign_local({}, {op}, __v)", l.0),
                    Root::Global(g) => format!("cx.assign_global({}, {op}, __v)", g.0),
                    _ => return None,
                };
                format!("let __v = {v};\nt!({call}, {s}, {e});\n")
            }
            StmtKind::If { cond, then, otherwise } => {
                let c = self.expr(cond, s, e)?;
                let mut tp = p.clone();
                tp.path.extend([0]);
                let then = self.nested(then, &tp, (s, e));
                let other = match otherwise {
                    Some(o) => {
                        let mut op = p.clone();
                        op.path.extend([1]);
                        format!(" else {{\n{}}}", self.nested(o, &op, (s, e)))
                    }
                    None => String::new(),
                };
                format!("if aot::truthy(&{c}) {{\n{then}}}{other}\n")
            }
            StmtKind::While { cond, body } => {
                let c = self.expr(cond, s, e)?;
                let mut bp = p.clone();
                bp.path.extend([0]);
                bp.in_loop = true;
                bp.depth += 1;
                let body = self.nested(body, &bp, (s, e));
                format!("loop {{\nif !aot::truthy(&{c}) {{ break; }}\n{body}}}\n")
            }
            StmtKind::ForRange { var, from, to, inclusive, body } => {
                let a = self.expr(from, s, e)?;
                let b = self.expr(to, s, e)?;
                let d = p.depth;
                let mut bp = p.clone();
                bp.path.extend([0]);
                bp.in_loop = true;
                bp.depth += 1;
                let inner = self.nested(body, &bp, (s, e));
                let end = if *inclusive { format!("__hi{d}.saturating_add(1)") } else { format!("__hi{d}") };
                format!(
                    "let __from{d} = {a};\nlet __to{d} = {b};\n\
                     let (Some(__lo{d}), Some(__hi{d})) = (__from{d}.whole(), __to{d}.whole()) else {{\n\
                     return Err(aot::at(Flow::Fault(aot::Fault::new(\"a range needs two whole numbers\")), {s}, {e}));\n}};\n\
                     let __end{d} = {end};\nlet mut __i{d} = __lo{d};\n\
                     while __i{d} < __end{d} {{\nlet __cur{d} = __i{d};\n__i{d} += 1;\n\
                     t!(cx.tick(), {s}, {e});\ncx.set({}, V::Int(__cur{d}));\n{inner}}}\n",
                    var.0
                )
            }
            StmtKind::Break if p.in_loop => "break;\n".to_string(),
            StmtKind::Continue if p.in_loop => "continue;\n".to_string(),
            StmtKind::Return(v) => match v {
                Some(v) => format!("return Ok({});\n", self.expr(v, s, e)?),
                None => "return Ok(V::None);\n".to_string(),
            },
            _ => return None,
        };
        Some(format!("{tick}{body}"))
    }

    /// A block inside a statement at `at`, as statements.
    fn nested(&mut self, b: &Block, p: &Place, at: (u32, u32)) -> String {
        self.block(b, p, Some(at), false)
    }

    /// `e` as a Rust expression giving a `V`, its failures placed at the
    /// statement `s..end`, or `None` when anything in it is not understood.
    fn expr(&mut self, e: &Expr, s: u32, end: u32) -> Option<String> {
        Some(match &e.kind {
            ExprKind::None => "V::None".into(),
            ExprKind::Bool(b) => format!("V::Bool({b})"),
            ExprKind::Int(i) => format!("V::Int({i}i64)"),
            ExprKind::Float(f) => format!("V::Float(f64::from_bits({:#x}))", f.to_bits()),
            ExprKind::Str(t) => format!("aot::text({t:?})"),
            ExprKind::Local(l) => format!("cx.get({})", l.0),
            ExprKind::Global(g) => format!("t!(cx.global({}), {s}, {end})", g.0),
            ExprKind::Check(x) => self.expr(x, s, end)?,
            ExprKind::Widen(x) => {
                format!("(match {} {{ V::Int(i) => V::Float(i as f64), o => o }})", self.expr(x, s, end)?)
            }
            ExprKind::Unary { op, expr } => {
                format!("{{ let __u = {}; t!(cx.unary(UnOp::{op:?}, __u), {s}, {end}) }}", self.expr(expr, s, end)?)
            }
            ExprKind::Binary { op, lhs, rhs } => {
                let (a, b) = (self.expr(lhs, s, end)?, self.expr(rhs, s, end)?);
                format!("{{ let __l = {a}; let __r = {b}; t!(cx.binary(BinOp::{op:?}, __l, __r), {s}, {end}) }}")
            }
            ExprKind::Logic { and, lhs, rhs } => {
                let (a, b) = (self.expr(lhs, s, end)?, self.expr(rhs, s, end)?);
                format!(
                    "{{ let __a = {a}; if aot::truthy(&__a) != {and} {{ V::Bool(aot::truthy(&__a)) }} \
                     else {{ V::Bool(aot::truthy(&{b})) }} }}"
                )
            }
            ExprKind::Coalesce { lhs, rhs } => {
                let (a, b) = (self.expr(lhs, s, end)?, self.expr(rhs, s, end)?);
                format!("{{ let __a = {a}; if matches!(__a, V::None) {{ {b} }} else {{ __a }} }}")
            }
            ExprKind::Template(parts) => {
                let mut code = String::from("{ let mut __s = String::new(); ");
                for part in parts {
                    let _ = write!(code, "__s.push_str(&({}).display()); ", self.expr(part, s, end)?);
                }
                code.push_str("aot::text(&__s) }");
                code
            }
            ExprKind::Call { callee: Callee::Fn(id), args } if !self.unit.fns.get(id.0 as usize)?.is_async => {
                let mut list = Vec::with_capacity(args.len());
                for a in args {
                    list.push(self.expr(a, s, end)?);
                }
                format!("{{ let __args = vec![{}]; t!(cx.call({}, __args), {s}, {end}) }}", list.join(", "), id.0)
            }
            _ => return None,
        })
    }
}

fn path_of(path: &[u32]) -> String {
    format!("[{}]", path.iter().map(|n| n.to_string()).collect::<Vec<_>>().join(", "))
}
