//! Rust from Rux's typed IR: step 9 of `docs/11-next.md`.
//!
//! [`generate`] writes a Rust module for a unit's functions. Each becomes a
//! Rust function running inside Rux's interpreter through `aot` (the
//! `rux_script::aot` module, reached by whatever path the generated crate
//! names it), in a frame of the interpreter's own. A statement whose every
//! expression the generator understands is compiled; any other statement is
//! handed back to the interpreter by its place in the function
//! (`aot::find`), in the same frame, so what is compiled and what is not can
//! sit side by side in one function. Control flow, `try`, `switch`, literals,
//! locals, state, operators, calls, fields, indexes, `?.` chains, methods,
//! writes through places and creating closures are compiled (a closure's
//! own body stays the interpreter's); `setInterval` is interpreted for now,
//! and [`Output`] counts both.
//!
//! The semantics are the interpreter's by construction: every operator,
//! read and write goes through the same `aot` call the interpreter makes,
//! steps are counted where it counts them, and a failure is placed at the
//! statement the interpreter would place it at.

use std::fmt::Write as _;

use rux_ir::ir::{BinOp, Block, Callee, Expr, ExprKind, Func, PlaceStep, Root, Stmt, StmtKind, Unit};

/// What [`generate`] wrote.
#[derive(Clone, Debug, Default)]
pub struct Output {
    /// The module's text.
    pub code: String,
    /// How many functions were compiled, and how many were left to the
    /// interpreter (`async fn`s, which run from their resumable form).
    pub functions: usize,
    pub skipped: usize,
    /// How many statements were compiled, and how many handed back.
    pub compiled: usize,
    pub handed_back: usize,
}

/// A module compiling `unit`'s functions, registered under `hash` by its
/// `install()`. `aot` is the path the generated code names the
/// `rux_script::aot` module by: `rux_runtime::aot` in an app's wrapper crate.
pub fn generate(unit: &Unit, hash: u64, aot: &str) -> Output {
    let mut g = Gen {
        unit,
        out: Output::default(),
        code: String::new(),
        frameless: false,
        strict: 0,
        refused: false,
        labels: 0,
        in_try: 0,
        func: 0,
        closures: Vec::new(),
    };
    let _ = writeln!(
        g.code,
        "// Generated by rux-codegen from a unit whose text hashes to {hash:#018x}.\n\
         // Edits are overwritten on the next build. See docs/11-next.md, step 9.\n\
         #![allow(unused_imports, unused_macros, unused_assignments, unused_mut, unused_variables, unused_braces, unused_parens, unused_labels, unreachable_code, \
         non_snake_case, clippy::all)]\n\
         use {aot}::{{self as aot, Cx, Flow, V, R, BinOp, UnOp}};\n\
         \n\
         /// A fallible step of a statement at `$s..$e`: its failure placed there.\n\
         macro_rules! t {{\n    ($x:expr, $s:expr, $e:expr) => {{\n        match $x {{\n            Ok(v) => v,\n            // u32::MAX: a function's value, whose failure its caller places.
            Err(err) => return Err(if $s == u32::MAX {{ err }} else {{ aot::at(err, $s, $e) }}),\n        }}\n    }};\n}}\n"
    );
    let mut table = Vec::new();
    for (id, f) in unit.fns.iter().enumerate() {
        if f.is_async {
            g.out.skipped += 1;
            continue;
        }
        let framed = g.func(id as u32, f);
        table.push(format!("({id}, {}, {framed}, f{id})", f.body.locals.len()));
        g.out.functions += 1;
    }
    let _ = writeln!(
        g.code,
        "\nstatic FNS: &[aot::Entry] = &[{}];\n\n\
         /// Register these functions for the text they were generated from.\n\
         pub fn install() {{\n    aot::register({hash:#018x}, FNS);\n}}",
        table.join(", ")
    );
    g.out.code = g.code;
    g.out
}

struct Gen<'u> {
    unit: &'u Unit,
    out: Output,
    code: String,
    /// Generating a function none of whose statements is handed back: its
    /// locals are Rust variables `l0`, `l1`, …, not the slots of a frame.
    frameless: bool,
    /// Inside a block used as a value: a statement there has no path the
    /// interpreter could be handed, so one that does not compile makes the
    /// whole expression not compile ([`Gen::refused`]).
    strict: usize,
    refused: bool,
    /// Labels handed out, so each `?.` chain, `switch` and `try` has its own.
    labels: usize,
    /// Inside the body of a `try`, which runs in a Rust closure: a `return`
    /// there leaves the closure as `Flow::Return` for the code after it.
    in_try: usize,
    /// The function being written, and the closures its body creates, in
    /// the order `rux_ir::ir::closures` numbers them (the interpreter finds
    /// one by its number).
    func: u32,
    closures: Vec<std::rc::Rc<rux_ir::ir::Closure>>,
}

/// Where a statement is and what it may do, for the code around it.
#[derive(Clone)]
struct Place {
    func: u32,
    /// Its path in the function's body, as `aot::find` reads one.
    path: Vec<u32>,
    /// Whether a Rust loop of the generated code is around it.
    in_loop: bool,
    /// How deep in generated loops, for names that must not collide.
    depth: usize,
    /// Directly in a `try`'s body, no loop between: a `break` or `continue`
    /// leaves the closure the body runs in, and the code after it acts.
    try_edge: bool,
}

impl Gen<'_> {
    /// Write function `id`, and say whether it runs in a frame: it does
    /// unless every statement of it compiled, when nothing of the
    /// interpreter's needs to see its locals.
    fn func(&mut self, id: u32, f: &Func) -> bool {
        let _ = writeln!(self.code, "\n/// `{}`", f.name.replace('\n', " "));
        let place = Place { func: id, path: Vec::new(), in_loop: false, depth: 0, try_edge: false };
        self.func = id;
        self.closures = rux_ir::ir::closures(&f.body.block);
        let counted = (self.out.compiled, self.out.handed_back);
        self.frameless = false;
        let framed = self.block(&f.body.block, &place, None, true);
        let framed_needed = self.out.handed_back > counted.1;
        let body = if framed_needed {
            let _ = writeln!(self.code, "fn f{id}(cx: &mut Cx, _args: Vec<V>) -> R<V> {{");
            framed
        } else {
            (self.out.compiled, self.out.handed_back) = counted;
            self.frameless = true;
            let body = self.block(&f.body.block, &place, None, true);
            self.frameless = false;
            let _ = writeln!(self.code, "fn f{id}(cx: &mut Cx, args: Vec<V>) -> R<V> {{");
            let mut prologue = String::from("let mut __args = args.into_iter();\n");
            for i in 0..f.body.locals.len() {
                if (i as u32) < f.params {
                    let _ = writeln!(prologue, "let mut l{i}: V = __args.next().unwrap_or(V::None);");
                } else {
                    let _ = writeln!(prologue, "let mut l{i}: V = V::None;");
                }
            }
            format!("{prologue}{body}")
        };
        self.code.push_str(&body);
        self.code.push_str("}\n");
        framed_needed
    }

    /// `b`'s statements. With `value`, the block's value is the function's
    /// result and is returned; otherwise it is worked out and dropped, as the
    /// interpreter does with a block run as a statement. `at` is the
    /// enclosing statement's place, where a failure in that value is placed.
    fn block(&mut self, b: &Block, place: &Place, at: Option<(u32, u32)>, value: bool) -> String {
        let mut s = String::new();
        let last = b.stmts.len();
        for (i, st) in b.stmts.iter().enumerate() {
            let mut p = place.clone();
            p.path.push(i as u32);
            if i + 1 == last && b.ty.is_some() {
                if let StmtKind::Expr(e) = &st.kind {
                    let (start, end) = at.unwrap_or((st.at.start, st.at.end));
                    // A function's value: its failure is its caller's to
                    // place, as the interpreter leaves it.
                    let (start, end) = if value { (u32::MAX, u32::MAX) } else { (start, end) };
                    match (self.expr(e, start, end), value, at) {
                        (Some(x), true, _) => {
                            self.out.compiled += 1;
                            let _ = writeln!(s, "cx.tick()?;\nreturn Ok({x});");
                        }
                        (Some(x), false, Some(_)) => {
                            self.out.compiled += 1;
                            let _ = writeln!(s, "cx.tick()?;\nlet _ = {x};");
                        }
                        _ => {
                            self.out.handed_back += 1;
                            let path = path_of(&p.path);
                            if value {
                                let _ = writeln!(s, "return cx.value({}, &{path});", p.func);
                            } else {
                                // Worked out as the interpreter works out a
                                // block's value, and dropped; a failure is
                                // placed at the enclosing statement.
                                let _ = writeln!(s, "let _ = t!(cx.value({}, &{path}), {start}, {end});", p.func);
                            }
                        }
                    }
                    return s;
                }
            }
            s.push_str(&self.stmt(st, &p));
        }
        if value {
            s.push_str("Ok(V::None)\n");
        }
        s
    }

    /// The statement handed back to the interpreter, in this frame, with
    /// what leaves it passed on.
    fn hand_back(&self, p: &Place) -> String {
        let path = path_of(&p.path);
        if p.in_loop {
            format!(
                "match cx.stmt({}, &{path}) {{ Ok(()) => {{}} Err(Flow::Break) => break, \
                 Err(Flow::Continue) => continue, Err(e) => return Err(e) }}",
                p.func
            )
        } else {
            format!("cx.stmt({}, &{path})?;", p.func)
        }
    }

    fn stmt(&mut self, st: &Stmt, p: &Place) -> String {
        if self.strict > 0 {
            return match self.try_stmt(st, p) {
                Some(code) => code,
                None => {
                    self.refused = true;
                    String::new()
                }
            };
        }
        match self.try_stmt(st, p) {
            Some(code) => {
                self.out.compiled += 1;
                code
            }
            None => {
                self.out.handed_back += 1;
                format!("{}\n", self.hand_back(p))
            }
        }
    }

    /// `st` compiled, or `None` when anything in it is not understood.
    fn try_stmt(&mut self, st: &Stmt, p: &Place) -> Option<String> {
        let (s, e) = (st.at.start, st.at.end);
        let tick = format!("t!(cx.tick(), {s}, {e});\n");
        let body = match &st.kind {
            StmtKind::Expr(x) => format!("let _ = {};\n", self.expr(x, s, e)?),
            StmtKind::Let { local, value } => {
                let v = match value {
                    Some(v) => self.expr(v, s, e)?,
                    None => "V::None".to_string(),
                };
                if self.frameless {
                    format!("l{} = {v};\n", local.0)
                } else {
                    format!("let __v = {v};\ncx.set({}, __v);\n", local.0)
                }
            }
            StmtKind::Assign { place, op, value } if place.steps.is_empty() => {
                let v = self.expr(value, s, e)?;
                let raw = *op;
                let op = match op {
                    Some(op) => format!("Some(BinOp::{op:?})"),
                    None => "None".to_string(),
                };
                let call = match place.root {
                    // A local of its own: nothing tracks it, so it is the
                    // interpreter's assignment without the tracking.
                    Root::Local(l) if self.frameless => {
                        return Some(format!(
                            "t!(cx.tick(), {s}, {e});\nlet __v = {v};\n{}",
                            match raw {
                                None => format!("l{} = __v;\n", l.0),
                                Some(raw) => format!(
                                    "let __t = std::mem::replace(&mut l{0}, V::None);\n\
                                     match cx.apply({1}, &__t, __v) {{ Ok(n) => l{0} = n, \
                                     Err(err) => {{ l{0} = __t; return Err(aot::at(err, {s}, {e})); }} }}\n",
                                    l.0,
                                    format!("BinOp::{raw:?}")
                                ),
                            }
                        ));
                    }
                    Root::Local(l) => format!("cx.assign_local({}, {op}, __v)", l.0),
                    Root::Global(g) => format!("cx.assign_global({}, {op}, __v)", g.0),
                    Root::Outer(_) => format!("cx.assign_at({}, &[], {op}, __v)", root_code(place.root)?),
                    Root::Capture(_) => return None,
                };
                format!("let __v = {v};\nt!({call}, {s}, {e});\n")
            }
            // Through fields and indexes: the keys worked out in order, then
            // the value, then the write, as the interpreter assigns.
            StmtKind::Assign { place, op, value } => {
                let mut keys = Vec::with_capacity(place.steps.len());
                for step in &place.steps {
                    keys.push(match step {
                        PlaceStep::Field(n) => format!("aot::key({n:?})"),
                        PlaceStep::Index(x) => format!("aot::Key::Index({})", self.expr(x, s, e)?),
                    });
                }
                let v = self.expr(value, s, e)?;
                let op = match op {
                    Some(op) => format!("Some(BinOp::{op:?})"),
                    None => "None".to_string(),
                };
                let call = match place.root {
                    Root::Local(l) if self.frameless => format!("cx.assign_in(&mut l{}, &__k, {op}, __v)", l.0),
                    root => format!("cx.assign_at({}, &__k, {op}, __v)", root_code(root)?),
                };
                format!("let __k = vec![{}];\nlet __v = {v};\nt!({call}, {s}, {e});\n", keys.join(", "))
            }
            StmtKind::If { cond, then, otherwise } => {
                let c = self.expr(cond, s, e)?;
                let mut tp = p.clone();
                tp.path.extend([0]);
                let then = self.nested(then, &tp, (s, e));
                let other = match otherwise {
                    Some(o) => {
                        let mut op = p.clone();
                        op.path.extend([1]);
                        format!(" else {{\n{}}}", self.nested(o, &op, (s, e)))
                    }
                    None => String::new(),
                };
                format!("if aot::truthy(&{c}) {{\n{then}}}{other}\n")
            }
            StmtKind::While { cond, body } => {
                let c = self.expr(cond, s, e)?;
                let mut bp = p.clone();
                bp.path.extend([0]);
                bp.in_loop = true;
                bp.try_edge = false;
                bp.depth += 1;
                let body = self.nested(body, &bp, (s, e));
                format!("loop {{\nif !aot::truthy(&{c}) {{ break; }}\n{body}}}\n")
            }
            StmtKind::ForRange { var, from, to, inclusive, body } => {
                let a = self.expr(from, s, e)?;
                let b = self.expr(to, s, e)?;
                let d = p.depth;
                let mut bp = p.clone();
                bp.path.extend([0]);
                bp.in_loop = true;
                bp.try_edge = false;
                bp.depth += 1;
                let inner = self.nested(body, &bp, (s, e));
                let end = if *inclusive { format!("__hi{d}.saturating_add(1)") } else { format!("__hi{d}") };
                format!(
                    "let __from{d} = {a};\nlet __to{d} = {b};\n\
                     let (Some(__lo{d}), Some(__hi{d})) = (__from{d}.whole(), __to{d}.whole()) else {{\n\
                     return Err(aot::at(Flow::Fault(aot::Fault::new(\"a range needs two whole numbers\")), {s}, {e}));\n}};\n\
                     let __end{d} = {end};\nlet mut __i{d} = __lo{d};\n\
                     while __i{d} < __end{d} {{\nlet __cur{d} = __i{d};\n__i{d} += 1;\n\
                     t!(cx.tick(), {s}, {e});\n{}\n{inner}}}\n",
                    if self.frameless {
                        format!("l{} = V::Int(__cur{d});", var.0)
                    } else {
                        format!("cx.set({}, V::Int(__cur{d}));", var.0)
                    }
                )
            }
            StmtKind::ForEach { var, counter, iter, body, .. } => {
                let over = self.expr(iter, s, e)?;
                let d = p.depth;
                let mut bp = p.clone();
                bp.path.extend([0]);
                bp.in_loop = true;
                bp.try_edge = false;
                bp.depth += 1;
                let inner = self.nested(body, &bp, (s, e));
                let set = |slot: u32, v: &str| {
                    if self.frameless {
                        format!("l{slot} = {v};\n")
                    } else {
                        format!("cx.set({slot}, {v});\n")
                    }
                };
                let mut each = set(var.0, &format!("__it{d}"));
                if let Some(c) = counter {
                    each.push_str(&set(c.0, &format!("V::Int(__n{d} as i64)")));
                }
                format!(
                    "let __over{d} = {over};\nlet __items{d} = t!(aot::items(__over{d}), {s}, {e});\n\
                     for (__n{d}, __it{d}) in __items{d}.into_iter().enumerate() {{\n\
                     t!(cx.tick(), {s}, {e});\n{each}{inner}}}\n"
                )
            }
            StmtKind::Throw(v) => format!("let __t = {};\nreturn Err(aot::at(aot::thrown(__t), {s}, {e}));\n", self.expr(v, s, e)?),
            StmtKind::Break if p.in_loop => "break;\n".to_string(),
            StmtKind::Continue if p.in_loop => "continue;\n".to_string(),
            StmtKind::Break if p.try_edge => "return Err(Flow::Break);\n".to_string(),
            StmtKind::Continue if p.try_edge => "return Err(Flow::Continue);\n".to_string(),
            StmtKind::Return(v) => {
                let v = match v {
                    Some(v) => self.expr(v, s, e)?,
                    None => "V::None".to_string(),
                };
                format!("{};\n", self.ret(&v))
            }
            StmtKind::Try { body, var, catch } => {
                // The body runs in a closure, so a failure anywhere in it (a
                // `t!`, a `?`) comes out as its value; what else leaves it
                // (`return`, `break`, `continue`) comes out as a `Flow` too
                // and is done here, as the interpreter passes it on.
                let n = self.label();
                let mut bp = p.clone();
                bp.path.extend([0]);
                bp.in_loop = false;
                bp.try_edge = true;
                self.in_try += 1;
                let inner = self.nested(body, &bp, (s, e));
                self.in_try -= 1;
                let mut cp = p.clone();
                cp.path.extend([1]);
                let handler = self.nested(catch, &cp, (s, e));
                let bind = match var {
                    Some(v) if self.frameless => format!("l{} = aot::caught(&__f);\n", v.0),
                    Some(v) => format!("cx.set({}, aot::caught(&__f));\n", v.0),
                    None => String::new(),
                };
                let (brk, cont) = if p.in_loop {
                    ("break", "continue")
                } else {
                    ("return Err(Flow::Break)", "return Err(Flow::Continue)")
                };
                format!(
                    "let __r{n}: R<()> = (|| -> R<()> {{\n{inner}Ok(())\n}})();\n\
                     match __r{n} {{\nOk(()) => {{}}\nErr(Flow::Fault(__f)) => {{\n{bind}{handler}}}\n\
                     Err(Flow::Return(__rv)) => {{ {}; }}\nErr(Flow::Break) => {brk},\nErr(Flow::Continue) => {cont},\n}}\n",
                    self.ret("__rv")
                )
            }
            _ => return None,
        };
        Some(format!("{tick}{body}"))
    }

    /// Leaving the function with `v`: from inside a `try`'s body, through
    /// the closure it runs in.
    fn ret(&self, v: &str) -> String {
        if self.in_try > 0 {
            format!("return Err(Flow::Return({v}))")
        } else {
            format!("return Ok({v})")
        }
    }

    fn label(&mut self) -> usize {
        self.labels += 1;
        self.labels
    }

    /// A field, index or method, `label` its chain's (`None` outside one):
    /// where a `?.` or `?[` meets `none`, the chain's value is `none`, as
    /// the interpreter's `step` leaves it.
    fn step(&mut self, e: &Expr, s: u32, end: u32, label: Option<usize>) -> Option<String> {
        let cut = |optional: bool| -> Option<String> {
            match (optional, label) {
                (false, _) => Some(String::new()),
                (true, Some(l)) => Some(format!("break 'c{l} V::None")),
                (true, None) => None,
            }
        };
        Some(match &e.kind {
            ExprKind::Field { base, name, optional } => {
                let stop = cut(*optional)?;
                let b = self.base(base, s, end, label)?;
                if *optional {
                    format!(
                        "{{ let __b = {b}; match t!(cx.field_opt(&__b, {name:?}), {s}, {end}) {{ Some(v) => v, None => {stop} }} }}"
                    )
                } else {
                    format!("{{ let __b = {b}; t!(cx.field(&__b, {name:?}), {s}, {end}) }}")
                }
            }
            ExprKind::Index { base, index, optional } => {
                let stop = cut(*optional)?;
                let b = self.base(base, s, end, label)?;
                let i = self.expr(index, s, end)?;
                if *optional {
                    format!(
                        "{{ let __b = {b}; let __i = {i}; \
                         match t!(cx.index_opt(&__b, &__i), {s}, {end}) {{ Some(v) => v, None => {stop} }} }}"
                    )
                } else {
                    format!("{{ let __b = {b}; let __i = {i}; t!(cx.index(&__b, &__i), {s}, {end}) }}")
                }
            }
            ExprKind::Method { recv, method, args, optional } => {
                let name = &method.name;
                // A method that changes its receiver, on a place: the place
                // is what changes, as the interpreter does it.
                if MUTATING.contains(&name.as_str()) && !*optional {
                    if let Some((root, steps)) = place_of(recv) {
                        let mut keys = Vec::with_capacity(steps.len());
                        for st in steps {
                            keys.push(match &st.kind {
                                ExprKind::Field { name, .. } => format!("aot::key({name:?})"),
                                ExprKind::Index { index, .. } => format!("aot::Key::Index({})", self.expr(index, s, end)?),
                                _ => return None,
                            });
                        }
                        let mut list = Vec::with_capacity(args.len());
                        for a in args {
                            list.push(self.expr(a, s, end)?);
                        }
                        let call = match root {
                            Root::Local(l) if self.frameless => {
                                format!("cx.method_in(&mut l{}, &__k, {name:?}, __args)", l.0)
                            }
                            root => format!("cx.method_at({}, &__k, {name:?}, __args)", root_code(root)?),
                        };
                        return Some(format!(
                            "{{ let __k = vec![{}]; let __args = vec![{}]; t!({call}, {s}, {end}) }}",
                            keys.join(", "),
                            list.join(", ")
                        ));
                    }
                }
                let stop = cut(*optional)?;
                let r = self.base(recv, s, end, label)?;
                let mut list = Vec::with_capacity(args.len());
                for a in args {
                    list.push(self.expr(a, s, end)?);
                }
                let check = if *optional { format!("if matches!(__m, V::None) {{ {stop} }} ") } else { String::new() };
                format!(
                    "{{ let __m = {r}; {check}let __args = vec![{}]; t!(cx.method(__m, {name:?}, __args), {s}, {end}) }}",
                    list.join(", ")
                )
            }
            _ => self.expr(e, s, end)?,
        })
    }

    /// The base of a step: the rest of its chain, or any other expression.
    fn base(&mut self, b: &Expr, s: u32, end: u32, label: Option<usize>) -> Option<String> {
        match &b.kind {
            ExprKind::Field { .. } | ExprKind::Index { .. } | ExprKind::Method { .. } => self.step(b, s, end, label),
            _ => self.expr(b, s, end),
        }
    }

    /// `b` as a Rust block expression giving its value, as the interpreter
    /// works out a block used as a value: its statements, then its last
    /// expression (ticked), or `none`. `None` when any of it does not
    /// compile: a statement in it has no path to hand back by.
    fn block_value(&mut self, b: &Block, s: u32, end: u32) -> Option<String> {
        let counted = (self.out.compiled, self.out.handed_back);
        let was = self.refused;
        self.refused = false;
        self.strict += 1;
        // No path: a hand-back is refused, and a `break` or `continue`
        // inside is left to the interpreter by not compiling the whole.
        let p = Place { func: u32::MAX, path: Vec::new(), in_loop: false, depth: 64, try_edge: false };
        let mut code = String::from("{\n");
        let last = b.stmts.len();
        let mut tail = "V::None".to_string();
        for (i, st) in b.stmts.iter().enumerate() {
            if i + 1 == last && b.ty.is_some() {
                if let StmtKind::Expr(e) = &st.kind {
                    match self.expr(e, s, end) {
                        Some(x) => tail = format!("{{ t!(cx.tick(), {s}, {end}); {x} }}"),
                        None => self.refused = true,
                    }
                    break;
                }
            }
            let code_st = self.stmt(st, &p);
            code.push_str(&code_st);
        }
        self.strict -= 1;
        let refused = self.refused;
        self.refused = was;
        (self.out.compiled, self.out.handed_back) = counted;
        if refused {
            return None;
        }
        code.push_str(&tail);
        code.push_str("\n}");
        Some(code)
    }

    /// A block inside a statement at `at`, as statements.
    fn nested(&mut self, b: &Block, p: &Place, at: (u32, u32)) -> String {
        self.block(b, p, Some(at), false)
    }

    /// `e` as a Rust expression giving a `V`, its failures placed at the
    /// statement `s..end`, or `None` when anything in it is not understood.
    fn expr(&mut self, e: &Expr, s: u32, end: u32) -> Option<String> {
        Some(match &e.kind {
            ExprKind::None => "V::None".into(),
            ExprKind::Bool(b) => format!("V::Bool({b})"),
            ExprKind::Int(i) => format!("V::Int({i}i64)"),
            ExprKind::Float(f) => format!("V::Float(f64::from_bits({:#x}))", f.to_bits()),
            ExprKind::Str(t) => format!("aot::text({t:?})"),
            ExprKind::Local(l) if self.frameless => format!("l{}.clone()", l.0),
            ExprKind::Local(l) => format!("cx.get({})", l.0),
            ExprKind::Global(g) => format!("t!(cx.global({}), {s}, {end})", g.0),
            ExprKind::Check(x) => self.expr(x, s, end)?,
            ExprKind::Widen(x) => {
                format!("(match {} {{ V::Int(i) => V::Float(i as f64), o => o }})", self.expr(x, s, end)?)
            }
            ExprKind::Unary { op, expr } => {
                format!("{{ let __u = {}; t!(cx.unary(UnOp::{op:?}, __u), {s}, {end}) }}", self.expr(expr, s, end)?)
            }
            ExprKind::Binary { op, lhs, rhs } => {
                let (a, b) = (self.expr(lhs, s, end)?, self.expr(rhs, s, end)?);
                let slow = format!("t!(cx.binary(BinOp::{op:?}, __l, __r), {s}, {end})");
                match fast_path(*op) {
                    // Rust's own operation when both values are the kind it
                    // is for; anything else, an overflow included, is the
                    // interpreter's operator, so the answer and the words of
                    // a failure are the same either way.
                    Some(fast) => format!(
                        "{{ let __l = {a}; let __r = {b}; \
                         match (&__l, &__r) {{ {fast} _ => {slow} }} }}"
                    )
                    .replace("SLOW", &format!("t!(cx.binary(BinOp::{op:?}, __l.clone(), __r.clone()), {s}, {end})")),
                    None => format!("{{ let __l = {a}; let __r = {b}; {slow} }}"),
                }
            }
            ExprKind::Logic { and, lhs, rhs } => {
                let (a, b) = (self.expr(lhs, s, end)?, self.expr(rhs, s, end)?);
                format!(
                    "{{ let __a = {a}; if aot::truthy(&__a) != {and} {{ V::Bool(aot::truthy(&__a)) }} \
                     else {{ V::Bool(aot::truthy(&{b})) }} }}"
                )
            }
            ExprKind::Coalesce { lhs, rhs } => {
                let (a, b) = (self.expr(lhs, s, end)?, self.expr(rhs, s, end)?);
                format!("{{ let __a = {a}; if matches!(__a, V::None) {{ {b} }} else {{ __a }} }}")
            }
            ExprKind::Template(parts) => {
                let mut code = String::from("{ let mut __s = String::new(); ");
                for part in parts {
                    let _ = write!(code, "__s.push_str(&({}).display()); ", self.expr(part, s, end)?);
                }
                code.push_str("aot::text(&__s) }");
                code
            }
            ExprKind::Call { callee, args } => {
                // The callee's value first, then the arguments in order, as
                // the interpreter works them out.
                let func = match callee {
                    Callee::Value(f) => Some(self.expr(f, s, end)?),
                    _ => None,
                };
                let mut list = Vec::with_capacity(args.len());
                for a in args {
                    list.push(self.expr(a, s, end)?);
                }
                let call = match callee {
                    Callee::Fn(id) if !self.unit.fns.get(id.0 as usize)?.is_async => format!("cx.call({}, __args)", id.0),
                    Callee::Fn(_) => return None,
                    Callee::Builtin(name) => format!("cx.builtin({name:?}, __args)"),
                    Callee::Native(key) => format!("cx.native({key:?}, __args)"),
                    Callee::Value(_) => "cx.call_value(__f, __args)".to_string(),
                    Callee::Dyn(name) => format!("cx.call_named({name:?}, __args)"),
                };
                let f = func.map(|f| format!("let __f = {f}; ")).unwrap_or_default();
                format!("{{ {f}let __args = vec![{}]; t!({call}, {s}, {end}) }}", list.join(", "))
            }
            ExprKind::If { cond, then, otherwise } => {
                let c = self.expr(cond, s, end)?;
                let t = self.block_value(then, s, end)?;
                let o = match otherwise {
                    Some(o) => self.block_value(o, s, end)?,
                    None => "{ V::None }".to_string(),
                };
                format!("(if aot::truthy(&{c}) {t} else {o})")
            }
            ExprKind::Block(b) => self.block_value(b, s, end)?,
            ExprKind::Array(items) => {
                let mut list = Vec::with_capacity(items.len());
                for i in items {
                    list.push(self.expr(i, s, end)?);
                }
                format!("aot::array(vec![{}])", list.join(", "))
            }
            ExprKind::Map(entries) => {
                let mut list = Vec::with_capacity(entries.len());
                for (k, v) in entries {
                    list.push(format!("({k:?}, {})", self.expr(v, s, end)?));
                }
                format!("aot::map(vec![{}])", list.join(", "))
            }
            ExprKind::Field { .. } | ExprKind::Index { .. } | ExprKind::Method { .. } => self.step(e, s, end, None)?,
            ExprKind::Chain(inner) => {
                let l = self.label();
                format!("('c{l}: {{ {} }})", self.base(inner, s, end, Some(l))?)
            }
            ExprKind::Outer(n) => format!("t!(cx.outer({n}), {s}, {end})"),
            // Its code stays the interpreter's; what it captures is read
            // here, in order, as the interpreter reads it.
            ExprKind::Closure(c) => {
                let k = self.closures.iter().position(|x| std::rc::Rc::ptr_eq(x, c))?;
                let mut caps = Vec::with_capacity(c.captures.len());
                for root in &c.captures {
                    caps.push(match root {
                        Root::Local(l) if self.frameless => format!("l{}.clone()", l.0),
                        Root::Local(l) => format!("cx.get({})", l.0),
                        root => format!("t!(cx.captured({}), {s}, {end})", root_code(*root)?),
                    });
                }
                format!("t!(cx.closure({}, {k}, vec![{}]), {s}, {end})", self.func, caps.join(", "))
            }
            ExprKind::Is { expr, ty } => {
                // The type as its text, read back once per thread; only when
                // that text reads back as the same type.
                let text = ty.to_string();
                if rux_ir::types::parse_type(&text).ok().as_ref() != Some(ty) {
                    return None;
                }
                let x = self.expr(expr, s, end)?;
                format!(
                    "{{ thread_local! {{ static __T: aot::Type = aot::type_of_text({text:?}); }} \
                     let __x = {x}; V::Bool(__T.with(|t| aot::is(&__x, t))) }}"
                )
            }
            ExprKind::Match { value, arms } => {
                let l = self.label();
                let v = self.expr(value, s, end)?;
                let mut code = format!("('m{l}: {{ let __sv{l} = {v};\n");
                for arm in arms {
                    let _ = writeln!(code, "{{ let mut __hit = {};", arm.patterns.is_empty());
                    for p in &arm.patterns {
                        let _ = writeln!(
                            code,
                            "if !__hit {{ let __p = {}; if aot::matches(&__p, &__sv{l}) {{ __hit = true; }} }}",
                            self.expr(p, s, end)?
                        );
                    }
                    let guard = match &arm.guard {
                        Some(g) => format!(" && aot::truthy(&{})", self.expr(g, s, end)?),
                        None => String::new(),
                    };
                    let body = self.block_value(&arm.body, s, end)?;
                    let _ = writeln!(code, "if __hit{guard} {{ break 'm{l} ({body}); }} }}");
                }
                code.push_str("V::None })");
                code
            }
            _ => return None,
        })
    }
}

/// The match arms that do `op` in Rust when both values are the kind it is
/// for, as the interpreter does it for those kinds; `SLOW` stands for the
/// interpreter's operator, which an `int` overflow falls back to so its
/// failure reads the same. `None` for an operator with no such arm.
fn fast_path(op: BinOp) -> Option<&'static str> {
    Some(match op {
        BinOp::AddInt => "(V::Int(x), V::Int(y)) => match x.checked_add(*y) { Some(v) => V::Int(v), None => SLOW },",
        BinOp::SubInt => "(V::Int(x), V::Int(y)) => match x.checked_sub(*y) { Some(v) => V::Int(v), None => SLOW },",
        BinOp::MulInt => "(V::Int(x), V::Int(y)) => match x.checked_mul(*y) { Some(v) => V::Int(v), None => SLOW },",
        BinOp::AddFloat => "(V::Float(x), V::Float(y)) => V::Float(x + y),",
        BinOp::SubFloat => "(V::Float(x), V::Float(y)) => V::Float(x - y),",
        BinOp::MulFloat => "(V::Float(x), V::Float(y)) => V::Float(x * y),",
        BinOp::Lt => "(V::Int(x), V::Int(y)) => V::Bool(x < y), (V::Float(x), V::Float(y)) => V::Bool(x < y),",
        BinOp::Le => "(V::Int(x), V::Int(y)) => V::Bool(x <= y), (V::Float(x), V::Float(y)) => V::Bool(x <= y),",
        BinOp::Gt => "(V::Int(x), V::Int(y)) => V::Bool(x > y), (V::Float(x), V::Float(y)) => V::Bool(x > y),",
        BinOp::Ge => "(V::Int(x), V::Int(y)) => V::Bool(x >= y), (V::Float(x), V::Float(y)) => V::Bool(x >= y),",
        BinOp::Eq => "(V::Int(x), V::Int(y)) => V::Bool(x == y), (V::Bool(x), V::Bool(y)) => V::Bool(x == y),",
        BinOp::Ne => "(V::Int(x), V::Int(y)) => V::Bool(x != y), (V::Bool(x), V::Bool(y)) => V::Bool(x != y),",
        _ => return None,
    })
}

/// The methods that change their receiver: a copy of the interpreter's list
/// (`rux_script::aot::MUTATING`), which `rux-aot-tests` holds this to.
pub const MUTATING: &[&str] = &[
    "push", "append", "pop", "shift", "insert", "remove", "clear", "truncate", "reverse", "sort", "set", "splice",
    "retain", "dedup", "drain", "pad", "replace", "make_upper", "make_lower", "unshift", "fill",
];

/// `root` as the generated code names it; `None` for a closure's capture,
/// which no compiled function has.
fn root_code(root: Root) -> Option<String> {
    Some(match root {
        Root::Local(l) => format!("aot::Root::Local(aot::LocalId({}))", l.0),
        Root::Global(g) => format!("aot::Root::Global(aot::GlobalId({}))", g.0),
        Root::Outer(n) => format!("aot::Root::Outer({n})"),
        Root::Capture(_) => return None,
    })
}

/// A receiver that is a place: a name, then fields and indexes with no `?`,
/// its steps root first. What the interpreter's `receiver` accepts.
fn place_of(e: &Expr) -> Option<(Root, Vec<&Expr>)> {
    let mut chain = Vec::new();
    let mut at = e;
    let root = loop {
        match &at.kind {
            ExprKind::Local(id) => break Root::Local(*id),
            ExprKind::Capture(i) => break Root::Capture(*i),
            ExprKind::Global(g) => break Root::Global(*g),
            ExprKind::Outer(n) => break Root::Outer(*n),
            ExprKind::Field { base, optional: false, .. } | ExprKind::Index { base, optional: false, .. } => {
                chain.push(at);
                at = base;
            }
            _ => return None,
        }
    };
    chain.reverse();
    Some((root, chain))
}

fn path_of(path: &[u32]) -> String {
    format!("[{}]", path.iter().map(|n| n.to_string()).collect::<Vec<_>>().join(", "))
}
